console.log('============== Padrões Criacionais ==============');
console.log();
require('./creational/singleton/singleton');
console.log();
require('./creational/factory-method/factory-method');
console.log();
require('./creational/abstract-factory/abstract-factory');
console.log();
require('./creational/builder/builder');
console.log();
require('./creational/prototype/prototype');
console.log();
console.log('=================================================');

console.log('============== Padrões Estrutural ==============');
console.log();
require('./structural/adapter/adapter');
console.log();
require('./structural/decorator/decorator');
console.log();
require('./structural/facade/facade');
console.log();
require('./structural/composite/composite');
console.log();
require('./structural/proxy/proxy');
console.log();
require('./structural/bridge/bridge');
console.log();
require('./structural/flyweight/flyweight');
console.log();
console.log('=================================================');