console.log('============== Padrões Criacionais ==============');
console.log();
require('./creational/singleton/singleton');
console.log();
require('./creational/factory-method/factory-method');
console.log();
require('./creational/abstract-factory/abstract-factory');
console.log();
require('./creational/builder/builder');
console.log();
console.log('=================================================');